"""initial migration - base state

Revision ID: ae847c4565e9
Revises: 
Create Date: 2025-06-03 22:21:13.224264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae847c4565e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_approved', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###